version: "3.1"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    networks:
      - golangnet
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ..:/workspace:cached
    command: sleep infinity

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ChatSystem
    networks:
      - golangnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    networks:
      - golangnet
    ports:
      - 8080:8080

networks:
  golangnet:
volumes:
  postgres-data:
